# Generated by Django 4.2.7 on 2023-11-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0249_hidden_if_item_available'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reusablemedium',
            new_name='pretixbase__identif_798d22_idx',
            old_fields=('identifier', 'type', 'organizer'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='applicable_to',
            field=models.ManyToManyField(null=True, to='pretixbase.itemcategory'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='locale',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
