# Generated by Django 4.2.7 on 2023-11-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0250_rename_reusablemedium_identifier_type_organizer_pretixbase__identif_798d22_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='applicable_to',
            new_name='applicable_to_categories',
        ),
    ]
