# Generated by Django 4.2.7 on 2023-11-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0251_rename_applicable_to_voucher_applicable_to_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='applicable_to_items',
            field=models.ManyToManyField(null=True, to='pretixbase.item'),
        ),
    ]
