# Generated by Django 4.2.7 on 2024-10-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0252_voucher_applicable_to_items'),
        ('pretixbase', '0254_alter_logentry_organizer_link_and_more'),
    ]

    operations = [
    ]
